parlante/parlante/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

from . import settings

from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from rest_framework import routers
from quickstart import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)
router.register(r'parlantes', views.ParlanteViewSet)

urlpatterns = [
    path('parlantes/', include('parlantes.urls')),
    path('admin/', admin.site.urls),
    url(r'^accounts/', include('registration.backends.default.urls')),
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('', include('pwa.urls')),
    path('oauth/', include('social_django.urls', namespace='social'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

parlante/parlantes/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('base', views.base, name = 'base'),
    path('tipo_parlante', views.tipo_parlante, name='tipo_parlante'),
    path('menu', views.menu, name='menu'),
    path('agregar', views.agregar, name='agregar'),
    path('agregar_parlante', views.agregar_parlante, name='agregar_parlante'),
    path('boton_buscar', views.boton_buscar, name='boton_buscar'),
    path('buscar_por_codigo', views.buscar_por_codigo, name='buscar_por_codigo'),
    path('eliminar', views.eliminar, name='eliminar'),
    path('eliminar_por_codigo', views.eliminar_por_codigo, name='eliminar_por_codigo'),
    path('editar', views.editar, name='editar'),
    path('editar_por_codigo', views.editar_por_codigo, name='editar_por_codigo'),
    path('actualizar_parlante', views.actualizar_parlante, name='actualizar_parlante'),
    path('listar', views.listar, name='listar'),
    path('mostrar_parlantes', views.mostrar_parlantes, name='mostrar_parlantes'),
    path('api', views.api, name='api'),
]

parlante/parlantes/models.py
from django.db import models

# Create your models here.

class Parlante(models.Model):
    id_parlante      = models.AutoField(db_column='id_parlante', primary_key=True)
    codigo           = models.CharField(max_length=10, unique=True)
    nombre           = models.CharField(max_length=20, blank=True, null=True)
    tipo             = models.CharField(max_length=10, blank=True, null=True)
    foto = models.ImageField(upload_to='fotos', blank=True, null=True)

    #toString
    def __str__(self):
        return  self.codigo+", "+self.nombre+", "+self.tipo+", " + self.foto.__str__()

    class Meta:
        ordering = ["nombre"]

parlante/parlantes/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
# Create your views here.

from parlantes.models import Parlante

def base(requeest):
    print("Estamos en la vista base..")
    context = {}
    return render(requeest, 'parlantes/base.html', context)

#decorador
@login_required
def menu(requeest):
    print("Estamos en la vista menu..")
    context = {}
    return render(requeest, 'parlantes/index.html', context)

#decorador
@login_required
def tipo_parlante(requeest):
    print("Estamos en la vista tipo parlante..")
    lista = Parlante.objects.all()
    context={'listado' : lista}
    return render(requeest, 'parlantes/tipoParlantes.html', context)

#decorador
@login_required
def agregar(request):
    print("ok, estamos en la vista agregarr")
    context={}
    return render(request, 'parlantes/crud/formulario_agregar.html', context)

#decorador
@login_required
def agregar_parlante(request):
    print("hola  estoy en agregar_parlante...")
    if request.method == 'POST':
       mi_codigo = request.POST['codigo']
       mi_nombre = request.POST['nombre']
       mi_tipo   = request.POST['tipo']
       mi_foto   = request.FILES['foto']

       if mi_nombre != "":
           if mi_tipo == 'bazucas' or mi_tipo == 'Karaoke' or mi_tipo == 'parlantes' or mi_tipo == "cubos" or mi_tipo == "deDJ":
               try:
                   parlante = Parlante()

                   parlante.codigo = mi_codigo
                   parlante.nombre = mi_nombre
                   parlante.tipo = mi_tipo
                   parlante.foto = mi_foto

                   parlante.save()

                   return render(request, 'parlantes/mensajes/datos_grabados.html', {})
               except parlante.DoesNotExist:
                   return render(request, 'parlantes/errores/error_204.html', {})
           else:
               return render(request, 'parlantes/errores/error_205.html', {})
       else:
           return render(request, 'parlantes/errores/error_201.html', {})
    else:
        return render(request, 'parlantes/errores/error_203.html', {})

#decorador
@login_required
def boton_buscar(request):
    print("ok, estamos en la vista boton buscar")
    context={}
    return render(request, 'parlantes/crud/boton_buscar.html', context)

#decorador
@login_required
def buscar_por_codigo(request):
    print("hola  estoy en buscar_por_codigo...")
    if request.method == 'POST':
       mi_codigo = request.POST['codigo']

       if mi_codigo != "":
           try:
               parlante = Parlante()
               parlante = Parlante.objects.get(codigo=mi_codigo)
               if parlante is not None:
                   print("Parlante=", parlante)
                   context={'parlante': parlante}
                   return render(request, 'parlantes/crud/mostrar_datos.html', context)
               else:
                   return render(request, 'parlantes/errores/error_202.html',{})
           except parlante.DoesNotExist:
               return render(request, 'parlantes/errores/error_202.html', {})
       else:
           return render(request, 'parlantes/errores/error_201.html', {})
    else:
        return render(request, 'parlantes/errores/error_203.html', {})

#decorador
@login_required
def eliminar(request):
    print("ok, estamos en la vista eliminar")
    context={}
    return render(request, 'parlantes/crud//boton_eliminar.html', context)

#decorador
@login_required
def eliminar_por_codigo(request):
    print("hola  estoy en eliminar_por_codigo...")
    if request.method == 'POST':
       mi_codigo = request.POST['codigo']

       if mi_codigo != "":
           try:
               parlante = Parlante()
               #parlante = Parlante.objects.all()
               parlante = Parlante.objects.get(codigo = mi_codigo)
               if parlante is not None:
                   print("Parlante=", parlante)
                   parlante.delete()
                   return render(request, 'parlantes/mensajes/parlante_eliminado.html', {})
               else:
                   return render(request, 'parlantes/errores/error_202.html',{})
           except parlante.DoesNotExist:
               return render(request, 'parlantes/errores/error_202.html', {})
       else:
           return render(request, 'parlantes/errores/error_201.html', {})
    else:
        return render(request, 'parlantes/errores/error_203.html', {})

#decorador
@login_required
def editar(request):
    print("ok, estamos en la vista editar")
    context = {}
    return render(request, 'parlantes/crud/boton_editar.html', context)

#decorador
@login_required
def editar_por_codigo(request):
    print("hola  estoy en editar_por_codigo...")
    if request.method == 'POST':
       mi_codigo = request.POST['codigo']

       if mi_codigo != "":
           try:
               parlante = Parlante()
               parlante = Parlante.objects.get(codigo = mi_codigo)
               if parlante is not None:
                   print("Parlante=", parlante)
                   context={'parlante': parlante}
                   return render(request, 'parlantes/crud/formulario_editar.html', context)
               else:
                   return render(request, 'parlantes/errores/error_202.html',{})
           except parlante.DoesNotExist:
               return render(request, 'parlantes/errores/error_202.html', {})
       else:
           return render(request, 'parlantes/errores/error_201.html', {})
    else:
        return render(request, 'parlantes/errores/error_203.html', {})

#decorador
@login_required
def actualizar_parlante(request):
    print("hola  estoy en actualizar_parlante...")
    if request.method == 'POST':

       mi_id     = request.POST['id_parlante']
       mi_codigp = request.POST['codigo']
       mi_nombre = request.POST['nombre']
       mi_tipo   = request.POST['tipo']
       mi_foto   = request.FILES['foto']

       if mi_nombre != "":
           if mi_tipo == 'bazucas' or mi_tipo == 'Karaoke' or mi_tipo == 'parlantes' or mi_tipo == "cubos" or mi_tipo == "deDJ":
               try:
                   parlante = Parlante()

                   parlante.id_parlante = mi_id
                   parlante.codigo = mi_codigp
                   parlante.nombre = mi_nombre
                   parlante.tipo = mi_tipo
                   parlante.foto = mi_foto

                   parlante.save()

                   return render(request, 'parlantes/mensajes/dato_editado.html',{})

               except parlante.DoesNotExist:
                   return render(request, 'parlantes/errores/error_204.html', {})
           else:
               return render(request, 'parlantes/errores/error_205.html', {})
       else:
           return render(request, 'parlantes/errores/error_201.html', {})
    else:
        return render(request, 'parlantes/errores/error_203.html', {})

def listar(request):
    print("ok, estamos en la vista listar")
    context={}
    return render(request, 'parlantes/crud/listar.html', context)

def mostrar_parlantes(request):
    print("ok, estamos en la vista mostrar parlantes")
    #lista = Parlante.objects.all()
    lista = Parlante.objects.filter(tipo = 'bazucas')
    context={'listado' : lista}
    return render(request, 'parlantes/crud/listar_parlantes.html', context)

def api(request):
    print("ok, estamos en la vista api")
    context={}
    return render(request, 'parlantes/youtubeApi.html', context)

parlante/parlantes/templates/parlantes/crud/boton_buscar.html
{% extends "parlantes/base.html" %}

{%block title %} Buscar parlante {% endblock%}

{% block content%}

<div id="caja2">

    <h1> Boton buscar</h1>
    <br>
    <br>

    <form action="buscar_por_codigo" method="post">
        {% csrf_token %}
        <label>Ingrese el codigo</label>
        <input type="text" name="codigo">
        <input class="waves-effect waves-light btn" type="submit" name="opcion" value="Buscar">
    </form>

</div>

{% endblock %}

{% block javascript%}

{% endblock %}

parlante/parlantes/templates/parlantes/crud/boton_editar.html
{% extends "parlantes/base.html" %}

{%block title %} Editar {% endblock%}

{% block content%}

<div id="caja2">

    <h1> Editar Parlante</h1>
    <br>
    <br>

    <form action="editar_por_codigo" method="post">
        {% csrf_token %}
        <label>Ingrese el codigo para modificar</label>
        <input type="text" name="codigo">
        <input class="waves-effect waves-light btn" type="submit" name="opcion" value="Buscar">
    </form>

</div>

{% endblock %}

{% block javascript%}

{% endblock %}

parlante/parlantes/templates/parlantes/crud/boton_eliminar.html
{% extends "parlantes/base.html" %}

{%block title %} Eliminar {% endblock%}

{% block content%}

<div id="caja2">

    <h1> Boton eliminar</h1>
    <br>
    <br>

    <form action="eliminar_por_codigo" method="post">
        {% csrf_token %}
        <label>Ingrese el codigo para eliminar</label>
        <input type="text" name="codigo">
        <input class="waves-effect waves-light btn" type="submit" name="opcion" value="Eliminar">
    </form>

</div>

{% endblock %}

{% block javascript%}

{% endblock %}

parlante/parlantes/templates/parlantes/crud/formulario_agregar.html
{% extends "parlantes/base.html" %}

{%block title %} Agregar {% endblock%}

{% block content%}


<div id="caja2">

        <h1>Agregar Parlante</h1>
        <br><br>

        <form action="agregar_parlante" method="post" enctype="multipart/form-data" class="col s12">
            {% csrf_token %}

            <div class="row">

                <div class="input-field col s12">
                  <input type="text" name="codigo">
                  <label>Codigo     :</label>
                </div>

                <div class="input-field col s12">
                  <input type="text" name="nombre">
                  <label>Nombre     :</label>
                </div>

                <div class="input-field col s12">
                  <input type="text" name="tipo">
                  <label>Tipo Parlante     :</label>
                    <!--<select name="tipo">
                         <option value="seleccionar" disabled>Seleccionar</option>
                         <option value="bazucas">Bazuca</option>
                         <option value="Karaoke">Karaoke</option>
                         <option value="parlantes">Parlante</option>
                         <option value="cubos">Cubo</option>
                         <option value="deDJ">De DJ</option>
                    </select>
                    <label>Tipo Parlante</label>
                    <br><br>-->
                </div>

                <div class="input-field col s12">
                  <tr><td><label>Foto     :</label><td>
                  <br><br>
                  <input type="file" name="foto">
                </div>
            </div>

            <input class="waves-effect waves-light btn" type="submit" name="opcion" value="Grabar">
        </form>

    </div>

{% endblock %}

{% block javascript%}

{% endblock %}

parlante/parlantes/templates/parlantes/crud/formulario_editar.html
{% extends "parlantes/base.html" %}
{% load static %}

{%block title %} Formulario Editar {% endblock%}

{% block content%}

<div id="caja2">

    <h1>Editar Dato de Parlante</h1>
    <br><br>
    <form action="actualizar_parlante" method="POST" enctype="multipart/form-data" class="col s12">
        {% csrf_token %}

        <div class="row">

                <input type="hidden" name="id_parlante" value="{{parlante.id_parlante}}">

                <div class="input-field col s12">
                  <label>Codigo   :</label><input type="text" name="codigo" value="{{parlante.codigo}}"><br>
                </div>

                <div class="input-field col s12">
                  <label>Nombre   :</label><input type="text" name="nombre" value="{{parlante.nombre}}"><br>
                </div>

                <div class="input-field col s12">

                    <input type="text" name="tipo" value="{{parlante.tipo}}">
                    <label>Tipo Parlante     :</label>
                    <!--<label>Tipo   :</label>

                     <select name="tipo" value="{{parlante.tipo}}">
                         <option value="Seleccionar" disabled>Seleccionar</option>
                         {% if parlante.tipo == "bazucas" %}
                             <option value="bazucas" selected>Bazuca</option>
                         {% else %}
                             <option value="bazucas">Bazuca</option>
                         {% endif %}

                         {% if parlante.tipo == "karaoke" %}
                             <option value="karaoke" selected>Karaoke</option>
                         {% else %}
                             <option value="karaoke">Karaoke</option>
                         {% endif %}

                         {% if parlante.tipo == "parlantes" %}
                             <option value="parlantes" selected>Parlante</option>
                         {% else %}
                             <option value="parlantes">Parlante</option>
                         {% endif %}

                         {% if parlante.tipo == "cubos" %}
                             <option value="cubos" selected>Cubo</option>
                         {% else %}
                             <option value="cubos">Cubo</option>
                         {% endif %}

                         {% if parlante.tipo == "deDJ" %}
                             <option value="deDJ" selected>De DJ</option>
                         {% else %}
                             <option value="deDJ">De DJ</option>
                         {% endif %}
                     </select>
                    <br><br>-->

                </div>

                <div class="input-field col s12">
                    <td><label>Foto     :</label><td>
                    <br><br>
                    <input type="file" name="foto" id="id_foto">
                    {% if parlante.foto %}
                        <tr><td><p>{{parlante.foto.url }}</p></td></tr>
                        <tr><td><p><img src="{{parlante.foto.url}}"></p></td></tr>
                    {% endif %}
                        <br><br>
                </div>
        </div>

        <input class="waves-effect waves-light btn" type="submit" name="opcion" value="Actualizar">
    </form>
</div>

{% endblock %}

{% block javascript%}

{% endblock %}

parlante/parlantes/templates/parlantes/crud/listar.html
{% extends "parlantes/base.html" %}

{%block title %} Listar {% endblock%}

{% block content%}

<div id="caja2">

    <h1> Boton Listar</h1>
    <br>
    <br>

    <form action="mostrar_parlantes" method="post">
        {% csrf_token %}
        <label>Precione el boton listar</label>
        <br><br>
        <input class="waves-effect waves-light btn" type="submit" name="opcion" value="Listar">
    </form>

</div>

{% endblock %}

{% block javascript%}

{% endblock %}

parlante/parlantes/templates/parlantes/crud/listar_parlantes.html
{% extends "parlantes/base.html" %}

{%block title %} listado de Parlante {% endblock%}

{% block content%}

<div id="caja2">

    <h1>Listado de Parlante</h1>

    <br><br>

    la cantidad de parlantes es {{ listado | length }} <br> <br>

    {% for parlante in listado %}
        {{ parlante.nombre}} - {{ parlante.tipo}}
        <br>
    {% endfor %}

</div>

{% endblock %}

{% block javascript%}

{% endblock %}

parlante/parlantes/templates/parlantes/crud/mostrar_datos.html
{% extends "parlantes/base.html" %}

{%block title %} Datos de Parlante {% endblock%}

{% block content%}

<div id="caja2">

    <h1>Mostrar datos de Parlante</h1>

    <br>
    <br>

    Los datos del Parlante son: {{ parlante }}

</div>

{% endblock %}

{% block javascript%}

{% endblock %}